spring:
  application:
    name: Serviceregistry

server:
  port: 8080
eureka:
  instance:
    hostname: https://travelbuddy-servicediscovery-production.up.railway.app/
  client:
    register-with-eureka: false
    fetch-registry: false
